version: "3.8"

services:
  client:
    image: node:20.0.0-alpine
    user: node
    entrypoint: sh -c
    working_dir: /home/node
    command: '"npm install && npm run dev"'
    ports:
      - 5173:5173
    volumes:
      - ./client:/home/node
    depends_on:
      - server

  server:
    image: node:20.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    entrypoint: sh -c
    command: '"npm install && npm run dev"'
    ports:
      - 8000:8000
    volumes:
      - ./server:/home/node
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=astroverse

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: astroverse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
