version: "3.8"

services:
  client:
    image: node:20.0.0-alpine
    user: node
    entrypoint: sh -c
    working_dir: /home/node
    command: '"npm install && npm run dev"'
    ports:
      - 5173:5173
    volumes:
      - ./client:/home/node
    depends_on:
      - server
    dns:
      - 8.8.8.8

  server:
    image: node:20.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    entrypoint: sh -c
    command: '"npm install && npm run dev"'
    ports:
      - 8000:8000
    volumes:
      - ./server:/home/node
      - ./server/.env:/home/node/.env  # Monter le fichier .env
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - DB_HOST=ce0lkuo944ch99.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com
      - DB_USER=uaja5q72u27152
      - DB_PASSWORD=pe68b14e81680e62fe19c22785ccdb6ac878d1f5d139d9e509b9c222d68bb673d
      - DB_NAME=d57n6c1r15fodr
      - DB_PORT=5432
      - DB_URI=mongodb+srv://ghlisyouri:xkrIicKRIlQhsquY@cluster0.omp14.mongodb.net/astroverse?retryWrites=true&w=majority&appName=Cluster0 # URI de MongoDB Atlas
    dns:
      - 8.8.8.8

  

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data:
